version: '3'

services:
  backend:
    image: 'go-dash'
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PW=postgres
      - DB_PORT=5432

      - PORT=3000

      - REDIS_PORT=6379
      - REDIS_HOST=redis-server
      - REDIS_DB=0
      - SECS_TO_EXPIRE=1000000s
    depends_on:
      - postgres
      - redis-server
  postgres:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"